services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hr_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@postgres/hr_db
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LLM_MODEL=openchat/openchat-7b
      - EMBEDDING_MODEL=jinaai/jina-embeddings-v2-base-en
      - REDIS_URL=redis://redis:6379
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - PYTHONPATH=/app/src
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data

volumes:
  postgres_: